upstream:
  default:
    - https://dns.google/dns-query
    - https://cloudflare-dns.com/dns-query
# accepted: dual, v4, v6
# default: dual
#connectIPVersion: dual
caching:
  minTime: 5m
  maxTime: 30m
  prefetching: true
  maxItemsCount: 0
filtering:
  queryTypes:
    - AAAA    
#port: 53
#tlsPort: 853
httpPort: 80
#httpsPort: 443
bootstrapDns: tcp+udp:208.67.222.222
# optional: Log level (one from debug, info, warn, error). Default: info
logLevel: info
# optional: Log format (text or json). Default: text
logFormat: json
# optional: log timestamps. Default: true
logTimestamp: true
# optional: obfuscate log output (replace all alphanumeric characters with *) for user sensitive data like request domains or responses to increase privacy. Default: false
logPrivacy: false

#prometheus设置
prometheus:
   enable: true
   path: /metrics
hostsFile:
  filePath: /etc/hosts
  hostsTTL: 60m
  refreshPeriod: 30m
